### PR TITLE
Upgrade github actions with new node version

### LINKED ISSUE #126: Deprecation warnings in Actions
There are several deprecation warnings in the logs on https://github.com/corona-warn-app/cwa-app-ccl/actions, for example in https://github.com/corona-warn-app/cwa-app-ccl/actions/runs/3321051924

"Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, richardsimko/update-tag, softprops/action-gh-release, actions/checkout"

"The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"

If left unadressed they may lead to workflow failures in the future.

### PR DESCRIPTION
**Pull request by brianebeling**
Fixes #126

This PR changes all the actions, however, it doesn't test all actions.
The pipeline for PR Validation / build (pull_request) triggers on PR and worked successfully.

I'd strongly recommend dry running the other pipelines as well, prior to merging.

---
Internal Tracking ID: [EXPOSUREAPP-14302](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14302)

### CODE REVIEW

**Comment by brianebeling** [comment]
Seems to work: https://github.com/corona-warn-app/cwa-app-ccl/actions/runs/3419483556/jobs/5693061213

**Comment by brianebeling** [comment]
I just noticed some dependencies might need additional updating, but I'm not entirely sure because of the limited test capability of this issue, without creating a local environment of sorts (private repo, some tool, ...)

Namely: richardsimko/update-tag and softprops/action-gh-release

**Comment by MikeMcC399** [comment]
@brianebeling 

- [richardsimko/update-tag](https://github.com/richardsimko/update-tag) looks like it was fixed in [v1.0.6](https://github.com/richardsimko/update-tag/releases/tag/v1.0.6) so there should be no need for a workflow update. @v1 will refer to the latest v1 version with the fix.

- [softprops/action-gh-release](https://github.com/softprops/action-gh-release) on the other hand has apparently not been fixed yet although there are open issues and PRs attempting to fix it.

**Comment by MikeMcC399** [comment]
- [softprops/action-gh-release](https://github.com/softprops/action-gh-release) has been fixed in https://github.com/softprops/action-gh-release/releases/tag/v0.1.15. Since there was no change to the major version it should not require any change to the CCL workflows to use the updated version.

**Comment by MikeMcC399** [comment]
@mlenkeit 

Since there seems to be a new CCL release planned I would suggest merging this PR.

The same action updates have been made in other repositories, e.g. cwa-website with positive results and no side-effects.

**Comment by mlenkeit** [comment]
@MikeMcC399 yes, I'll include these changes.

**Pull request merged**
