### PR TITLE
Adapted Testcases according to latest Excel

### PR DESCRIPTION
**Pull request by hermesmar**

### CODE REVIEW

**Comment by Ein-Tim** [comment]
I See no reason why the validity of PCR tests is 72h and not 48h. See https://github.com/corona-warn-app/cwa-documentation/issues/819#issuecomment-1020008222. 

PCR tests in Germany are valid 48h and for entering Germany also 48h. @mlenkeit

**Comment by mlenkeit** [comment]
> I See no reason why the validity of PCR tests is 72h and not 48h. See [corona-warn-app/cwa-documentation#819 (comment)](https://github.com/corona-warn-app/cwa-documentation/issues/819#issuecomment-1020008222).
> 
> PCR tests in Germany are valid 48h and for entering Germany also 48h. @mlenkeit

@Ein-Tim I understand and see the discrepancy. However, at the moment, we have been requested to stick with 72/48h. We will continue to raise awareness for this inconsistency.

**Comment by vaubaehn** [comment]
Is the CCL a Germany-only solution? If they're expected be adopted for other (EU) countries, it could help in testing to stick with the 72hrs for PCR for nations with such rules while it makes not much of a difference for DE...

**Comment by mlenkeit** [comment]
> Is the CCL a Germany-only solution? If they're expected to be adopted for other (EU) countries, it could help in testing to stick with the 72hrs for PCR for nations with such rules while it makes not much of a difference for DE...

@vaubaehn CCL is currently a Germany-only approach. If other countries want to adopt it (e.g. as a fork), we won't stop them of course, but we are not actively promoting it either 😉

**Comment by vaubaehn** [comment]
> > Is the CCL a Germany-only solution? If they're expected to be adopted for other (EU) countries, it could help in testing to stick with the 72hrs for PCR for nations with such rules while it makes not much of a difference for DE...
> 
> @vaubaehn CCL is currently a Germany-only approach. If other countries want to adopt it (e.g. as a fork), we won't stop them of course, but we are not actively promoting it either.

@mlenkeit Ok, thanks, good to know :)

**Pull request merged**
