### PR TITLE
Feature: Support reissuing of expired certificates (EXPOSUREAPP-12970)

### PR DESCRIPTION
**Pull request by mlenkeit**

### CODE REVIEW

**Review by KathrinLuecke — APPROVED** [review]
UA approved

**Comment by Ein-Tim** [comment]
Will this feature be released together with version 2.22?

**Comment by KathrinLuecke** [comment]
Hi @Ein-Tim, the  re-issuing of expired certificates comes with 2.23.

**Comment by mlenkeit** [comment]
Accidentally closed and cannot be re-opened, see https://github.com/corona-warn-app/cwa-app-ccl/pull/76 instead

**Pull request closed without merging**
